### ISSUE TITLE
Seem that there are some missing file in the linux executable

### ISSUE THREAD

**Issue by SHF101202021** [gatk555/ngspice#1]
# Statement

When I try to exexcute ```bin/ngspice``` in my RedHat 7 system, my terminal show the following messages:
> bin/ngspice: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory

Hence, I try to compare to the executable released by [official ngspice](https://ngspice.sourceforge.io/experimental/ngspice-40plus-pre-master.7z). 

These are my finding:

1.  Lack of one dll file in bin folder
2.  Content of library seems to be different

### Comparison Table
| Folder Name | Window Executable | Linux Executalbe |
| :---: |  :----: | :----: |
| Bin | ![image](https://github.com/gatk555/ngspice/assets/88426850/8a584a22-5004-47b0-9555-12194187e3db) | ![image](https://github.com/gatk555/ngspice/assets/88426850/05f32543-9bc8-4d32-a994-10b07f5d727c)|
| Lib  | ![image](https://github.com/gatk555/ngspice/assets/88426850/72d320a3-e2df-4cdb-89c0-545f10ad45c6) |   ![image](https://github.com/gatk555/ngspice/assets/88426850/aefad143-0f3e-4f2e-97aa-636ac03c97ae)) | 

# Problem

My question: are these files are excluded in you building plan?
If yes, is there any way to recover this situation?

Thanks in advanced
Szuhsien

**Comment by gatk555** [comment]
There are two separate issues here: a missing shared library, and different file lists between Windows and Linux builds.

1. libtlinfo.so.6: this looks like a simple case of a missing OS dependency; you need to install it.  However, if you are really running Red Hat 7, that is not surprising, the OS is 23 years old!  With such an old system probably the only way would be to build it from source code, and it would be simpler to do that with ngspice instead.

2. These differences are expected.  On Linux the support library for OpenMP is a system dependency, but it seems that it must be supplied with the binary on Windows builds using visual studio.  The Linux build of ngspice does not have separate graphical and "console" versions.  It runs from a shell window ("console") until you use the "plot" command, then GUI appears.  The *.osdi files are not actually part of ngspice but are included in those Windows builds as an extra.  When ngspice is built from source in the standard way they are not included.  The ngspice manual describes how to build them.  The builds here are almost completely standard, in that they are made using the compile scripts included with the source code.

**Comment by gatk555** [comment]
No further comment, so assumed to be fixed.
