### ISSUE TITLE
Windows Security blocked latest download...

### ISSUE THREAD

**Issue by tomhajjar** [gatk555/ngspice#2]
Windows Security blocked latest download and also deleted previous download from last week.

Had to override it...

![2024-12-10_042205](https://github.com/user-attachments/assets/c4fbb4c6-dfcd-4f73-bc8d-1ae132052074)
![2024-12-10_041953](https://github.com/user-attachments/assets/0280bc24-e172-4d3d-879c-63cab61b532b)
![2024-12-10_042024](https://github.com/user-attachments/assets/7583133d-e302-44fb-885a-ef3544d3216e)

**Comment by gatk555** [comment]
My guess is that it is a false positive.  The scanner seems to be reporting the problem with the ZIP file.  If it has matched a byte sequence in the file, that means nothing as the process of compression can produce almost any sequence.

The other possibilities are that there is some evil code in Ngspice, or the github VM image has been compromised.  Both seem extremely unlikely, and if it is the second we should soon hear about it.

The only thing I can think of doing that might help is to pre-compress the package before exporting it.  That means it will be double-wrapped, and harder to install,  but should stop these reports.  But if this is a false positive then it should go away over time.

**Comment by tomhajjar** [comment]
This mornings download didn't get flagged....

**Comment by gatk555** [comment]
Seems to have fixed itself.
